name: Laravel CI/CD

on:
  push:
    branches: [ main ]

jobs:
  laravel-tests:
    name: CI
    runs-on: ubuntu-latest

    steps:
    - uses: shivammathur/setup-php@15c43e89cdef867065b0213be354c2841860869e
      with:
        php-version: '8.0'
    - uses: actions/checkout@v2
    - name: Copiando o  .env
      run: php -r "file_exists('.env') || copy('.env.example', '.env');"
    - name: Instalando Dependencias
      run: composer install -q --no-ansi --no-interaction --no-scripts --no-progress --prefer-dist
    - name: Gerando a Key
      run: php artisan key:generate
    - name: Ajustando Permissões #️⃣
      run: chmod -R 777 storage bootstrap/cache
    - name: Criando Banco para Testes ‼️‼️‼️
      run: |
        mkdir -p database
        touch database/database.sqlite
    - name: Executando Testes
      env:
        DB_CONNECTION: sqlite
        DB_DATABASE: database/database.sqlite
      run: vendor/bin/phpunit
    - name: Psalm Security Scan
      uses: docker://ghcr.io/psalm/psalm-security-scan
      with:
        security_analysis: true

    - name: Upload Security Analysis results to GitHub
      uses: github/codeql-action/upload-sarif@v1
      with:
        sarif_file: results.sarif

  laravel-deployment:
    name: CD
    needs: laravel-tests
    runs-on: ubuntu-latest
    steps:
      - name: Executando comandos SSH 🚀
        uses: appleboy/ssh-action@master
        with:
          host: ${{ secrets.SSH_HOST }}
          username: ${{ secrets.SSH_USER }}
          key: ${{ secrets.SSH_PRIVATE_KEY }}
          port: ${{ secrets.SSH_PORT }}
          script: |
            ls -la


